name: daily_exercise_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^1.0.0
  flutter_launcher_icons: ^0.9.2  # Add launcher icon dependency if you plan to change the app icon

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf

  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true

  # Add flutter_launcher_icons configuration if you want to use custom app icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Specify path to your app icon

# Note: If you want to add any other resources or modify any other sections, feel free to do so.
